/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
export async function seed (knex) {
  // Deletes ALL existing entries
  await knex("movies").del();
  await knex("movies").insert([
    { id: 1,   name: "Inception",                          type: 8 },
    { id: 2,   name: "Star Wars",                          type: 8 },
    { id: 3,   name: "Platoon",                            type: 13 },
    { id: 4,   name: "Seven",                              type: 11 },
    { id: 5,   name: "Superbad",                           type: 5 },
    { id: 6,   name: "Procurando Nemo",                    type: 4 },
    { id: 7,   name: "O Bebê de Rosemary",                 type: 9 },
    { id: 8,   name: "The Godfather",                      type: 7 },
    { id: 9,   name: "The Dark Knight",                    type: 2 },
    { id: 10,  name: "Pulp Fiction",                       type: 7 },
    { id: 11,  name: "Schindler's List",                   type: 13 },
    { id: 12,  name: "The Shawshank Redemption",           type: 7 },
    { id: 13,  name: "Avengers: Endgame",                  type: 8 },
    { id: 14,  name: "Toy Story",                          type: 4 },
    { id: 15,  name: "The Lion King",                      type: 4 },
    { id: 16,  name: "Finding Dory",                       type: 4 },
    { id: 17,  name: "Monsters Inc.",                      type: 4 },
    { id: 18,  name: "Zootopia",                           type: 4 },
    { id: 19,  name: "Frozen",                             type: 4 },
    { id: 20,  name: "The Exorcist",                       type: 9 },
    { id: 21,  name: "Get Out",                            type: 9 },
    { id: 22,  name: "It",                                 type: 9 },
    { id: 23,  name: "A Quiet Place",                      type: 9 },
    { id: 24,  name: "Us",                                 type: 9 },
    { id: 25,  name: "Hereditary",                         type: 9 },
    { id: 26,  name: "The Shining",                        type: 9 },
    { id: 27,  name: "Psycho",                             type: 9 },
    { id: 28,  name: "The Sixth Sense",                    type: 11 },
    { id: 29,  name: "Gone Girl",                          type: 11 },
    { id: 30,  name: "Prisoners",                          type: 11 },
    { id: 31,  name: "Knives Out",                         type: 11 },
    { id: 32,  name: "Shutter Island",                     type: 11 },
    { id: 33,  name: "The Girl with the Dragon Tattoo",    type: 11 },
    { id: 34,  name: "The Great Gatsby",                   type: 12 },
    { id: 35,  name: "Pride and Prejudice",                type: 12 },
    { id: 36,  name: "La La Land",                         type: 12 },
    { id: 37,  name: "Titanic",                            type: 12 },
    { id: 38,  name: "A Star Is Born",                     type: 12 },
    { id: 39,  name: "The Notebook",                       type: 12 },
    { id: 40,  name: "The Avengers",                       type: 8 },
    { id: 41,  name: "Iron Man",                           type: 8 },
    { id: 42,  name: "Guardians of the Galaxy",            type: 8 },
    { id: 43,  name: "Black Panther",                      type: 8 },
    { id: 44,  name: "Doctor Strange",                     type: 8 },
    { id: 45,  name: "Thor: Ragnarok",                     type: 8 },
    { id: 46,  name: "Captain America: The Winter Soldier",type: 8 },
    { id: 47,  name: "Spider-Man: Homecoming",             type: 8 },
    { id: 48,  name: "Logan",                              type: 8 },
    { id: 49,  name: "Deadpool",                           type: 5 },
    { id: 50,  name: "Ant-Man",                            type: 5 },
    { id: 51,  name: "Joker",                              type: 7 },
    { id: 52,  name: "The Irishman",                       type: 7 },
    { id: 53,  name: "Once Upon a Time in Hollywood",      type: 7 },
    { id: 54,  name: "1917",                               type: 13 },
    { id: 55,  name: "Dunkirk",                            type: 13 },
    { id: 56,  name: "Saving Private Ryan",                type: 13 },
    { id: 57,  name: "Hacksaw Ridge",                      type: 13 },
    { id: 58,  name: "The Revenant",                       type: 2 },
    { id: 59,  name: "Mad Max: Fury Road",                 type: 2 },
    { id: 60,  name: "The Matrix",                         type: 8 },
    { id: 61,  name: "Interstellar",                       type: 8 },
    { id: 62,  name: "Dune",                               type: 8 },
    { id: 63,  name: "Blade Runner 2049",                  type: 8 },
    { id: 64,  name: "Gravity",                            type: 8 },
    { id: 65,  name: "The Martian",                        type: 8 },
    { id: 66,  name: "Alien",                              type: 8 },
    { id: 67,  name: "Avatar",                             type: 8 },
    { id: 68,  name: "Coco",                               type: 4 },
    { id: 69,  name: "Ratatouille",                        type: 4 },
    { id: 70,  name: "Up",                                 type: 4 },
    { id: 71,  name: "Inside Out",                         type: 4 },
    { id: 72,  name: "Moana",                              type: 4 },
    { id: 73,  name: "Aladdin",                            type: 4 },
    { id: 74,  name: "Mulan",                              type: 4 },
    { id: 75,  name: "Beauty and the Beast",               type: 4 },
    { id: 76,  name: "Frozen II",                          type: 4 },
    { id: 77,  name: "The Little Mermaid",                 type: 4 },
    { id: 78,  name: "The Incredibles",                    type: 4 },
    { id: 79,  name: "The Jungle Book",                    type: 4 },
    { id: 80,  name: "Tangled",                            type: 4 },
    { id: 81,  name: "The Princess and the Frog",          type: 4 },
    { id: 82,  name: "The Polar Express",                  type: 4 },
    { id: 83,  name: "How to Train Your Dragon",           type: 4 },
    { id: 84,  name: "Kung Fu Panda",                      type: 4 },
    { id: 85,  name: "Shrek",                              type: 4 },
    { id: 86,  name: "Despicable Me",                      type: 4 },
    { id: 87,  name: "Sing",                               type: 4 },
    { id: 88,  name: "The Secret Life of Pets",            type: 4 },
    { id: 89,  name: "Ice Age",                            type: 4 },
    { id: 90,  name: "Happy Feet",                         type: 4 },
    { id: 91,  name: "The Lego Movie",                     type: 4 },
    { id: 92,  name: "Cars",                               type: 4 },
    { id: 93,  name: "WALL-E",                             type: 4 },
    { id: 94,  name: "Cloudy with a Chance of Meatballs",  type: 4 },
    { id: 95,  name: "Monsters vs. Aliens",                type: 4 },
    { id: 96,  name: "Home",                               type: 4 },
    { id: 97,  name: "Big Hero 6",                         type: 4 },
    { id: 98,  name: "Brave",                              type: 4 },
    { id: 99,  name: "The Croods",                         type: 4 },
    { id: 100, name: "The Good Dinosaur",                  type: 4 },
    { id: 101, name: "Over the Moon",                      type: 4 },
    { id: 102, name: "Soul",                               type: 4 },
    { id: 103, name: "The Mitchells vs. the Machines",     type: 4 },
    { id: 104, name: "Rio",                                type: 4 },
    { id: 105, name: "Ferdinand",                          type: 4 },
    { id: 106, name: "Madagascar",                         type: 4 },
    { id: 107, name: "Megamente",                          type: 4 },
    { id: 108, name: "Hotel Transilvânia",                 type: 4 },
    { id: 109, name: "Encanto",                            type: 4 },
    { id: 110, name: "Luca",                               type: 4 },
    { id: 111, name: "Bolt",                               type: 4 },
    { id: 112, name: "Surf's Up",                          type: 4 },
    { id: 113, name: "Zambezia",                           type: 4 },
    { id: 114, name: "Frozen Fever",                       type: 4 },
    { id: 115, name: "Minions",                            type: 4 },
    { id: 116, name: "Coraline",                           type: 9 },
    { id: 117, name: "ParaNorman",                         type: 9 },
    { id: 118, name: "Kubo e as Cordas Mágicas",           type: 4 },
    { id: 119, name: "Frankenweenie",                      type: 9 },
    { id: 120, name: "A Noiva Cadáver",                    type: 9 },
    { id: 121, name: "A Fantástica Fábrica de Chocolate",  type: 5 },
    { id: 122, name: "Edward Mãos de Tesoura",             type: 7 },
    { id: 123, name: "O Estranho Mundo de Jack",           type: 4 },
    { id: 124, name: "Sweeney Todd",                       type: 10 },
    { id: 125, name: "Charlie e a Fantástica Fábrica de Chocolate", type: 4 },
    { id: 126, name: "Piratas do Caribe",                  type: 3 },
    { id: 127, name: "O Hobbit",                           type: 3 },
    { id: 128, name: "O Senhor dos Anéis: A Sociedade do Anel", type: 3 },
    { id: 129, name: "O Senhor dos Anéis: As Duas Torres", type: 3 },
    { id: 130, name: "O Senhor dos Anéis: O Retorno do Rei", type: 3 },
    { id: 131, name: "Jumanji",                            type: 3 },
    { id: 132, name: "O Livro da Selva",                   type: 4 },
    { id: 133, name: "Cinderela",                          type: 12 },
    { id: 134, name: "Malévola",                           type: 12 },
    { id: 135, name: "Bela Adormecida",                    type: 12 },
    { id: 136, name: "Branca de Neve e os Sete Anões",     type: 12 },
    { id: 137, name: "Peter Pan",                          type: 4 },
    { id: 138, name: "Dumbo",                              type: 4 },
    { id: 139, name: "Hércules",                           type: 4 },
    { id: 140, name: "Moana: Um Mar de Aventuras",         type: 4 },
    { id: 141, name: "Lilo e Stitch",                      type: 4 },
    { id: 142, name: "Tarzan",                             type: 4 },
    { id: 143, name: "Atlantis: O Reino Perdido",          type: 4 },
    { id: 144, name: "Os Pinguins de Madagascar",          type: 4 },
    { id: 145, name: "Shrek 2",                            type: 4 },
    { id: 146, name: "Shrek Para Sempre",                  type: 4 },
    { id: 147, name: "Gato de Botas",                      type: 4 },
    { id: 148, name: "Kung Fu Panda 2",                    type: 4 },
    { id: 149, name: "Kung Fu Panda 3",                    type: 4 },
    { id: 150, name: "Como Treinar o Seu Dragão 2",        type: 4 },
    { id: 151, name: "Como Treinar o Seu Dragão 3",        type: 4 },
    { id: 152, name: "Homem-Aranha no Aranhaverso",        type: 8 },
    { id: 153, name: "Os Incríveis 2",                     type: 4 },
    { id: 154, name: "O Rei Leão (2019)",                  type: 4 },
    { id: 155, name: "Os Croods: Uma Nova Era",            type: 4 },
    { id: 156, name: "Trolls",                             type: 4 },
    { id: 157, name: "Trolls 2",                           type: 4 },
    { id: 158, name: "A Era do Gelo 2",                    type: 4 },
    { id: 159, name: "A Era do Gelo 3",                    type: 4 },
    { id: 160, name: "A Era do Gelo 4",                    type: 4 },
    { id: 161, name: "A Era do Gelo 5",                    type: 4 },
    { id: 162, name: "Rio 2",                              type: 4 },
    { id: 163, name: "Sing 2",                             type: 4 },
    { id: 164, name: "Encanto",                            type: 4 },
    { id: 165, name: "Soul",                               type: 4 },
    { id: 166, name: "Luca",                               type: 4 },
    { id: 167, name: "Turning Red",                        type: 4 },
    { id: 168, name: "Pinóquio",                           type: 4 },
    { id: 169, name: "Encanto",                            type: 4 },
    { id: 170, name: "Wreck-It Ralph",                     type: 4 },
    { id: 171, name: "Ralph Breaks the Internet",          type: 4 },
    { id: 172, name: "Frozen II",                          type: 4 },
    { id: 173, name: "Zootopia",                           type: 4 },
    { id: 174, name: "Big Hero 6",                         type: 4 },
    { id: 175, name: "Cinderela (2015)",                   type: 12 },
    { id: 176, name: "Alice no País das Maravilhas",       type: 4 },
    { id: 177, name: "Alice Através do Espelho",           type: 4 },
    { id: 178, name: "Peter Rabbit",                       type: 4 },
    { id: 179, name: "Os Smurfs",                          type: 4 },
    { id: 180, name: "Os Smurfs e a Vila Perdida",         type: 4 },
    { id: 181, name: "Paddington",                         type: 4 },
    { id: 182, name: "Paddington 2",                       type: 4 },
    { id: 183, name: "Alvin e os Esquilos",                type: 4 },
    { id: 184, name: "Alvin e os Esquilos 2",              type: 4 },
    { id: 185, name: "Alvin e os Esquilos 3",              type: 4 },
    { id: 186, name: "Alvin e os Esquilos 4",              type: 4 },
    { id: 187, name: "Happy Feet 2",                       type: 4 },
    { id: 188, name: "O Expresso Polar",                   type: 4 },
    { id: 189, name: "Operação Big Hero",                  type: 4 },
    { id: 190, name: "Os Sem-Floresta",                    type: 4 },
    { id: 191, name: "Espanta Tubarões",                   type: 4 },
    { id: 192, name: "Bee Movie",                          type: 4 },
    { id: 193, name: "O Parque dos Sonhos",                type: 4 },
    { id: 194, name: "Os Boxtrolls",                       type: 4 },
    { id: 195, name: "Pequenos Espiões",                   type: 2 },
    { id: 196, name: "Pequenos Espiões 2",                 type: 2 },
    { id: 197, name: "Pequenos Espiões 3",                 type: 2 },
    { id: 198, name: "Pequenos Espiões 4",                 type: 2 },
    { id: 199, name: "Desventuras em Série",               type: 4 },
    { id: 200, name: "Eragon",                             type: 3 }
  ]);
};
